
name: Creating-docker-image

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"    
   

jobs:
  creating-docker-image:
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      strategy:
         max-parallel: 1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12.14.1'
        - name: login to dockerHub
          uses: docker/login-action@v1
          with: 
             username: ${{ secrets.DOCKER_HUB_USER }}
             password:  ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Get the tag name
          run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: aayushkumar2000/blognow-service-publish:${{ env.TAG }}
       
      
